### ISSUE TITLE
add github commands cheatsheet

### ISSUE THREAD

**Issue by pwnb0y** [pwnb0y/PumpkinShell#12]

**Comment by AtharvaTwS** [comment]
hey Vicky, when your talking about this cheatsheet, in which format your asking for (markdown file or something related ?)

**Comment by pwnb0y** [comment]
hello @AtharvaTwS we receive only markdown file.

**Comment by Ajiboso-Adeola** [comment]
I would love to contribute  on this issue

**Comment by pwnb0y** [comment]
hey @Ajiboso-Adeola you can go on with it best luck 👍
